actors:
  r7kamura:
    image_url: /images/actors/r7kamura.jpg
    name: r7kamura
    url: https://twitter.com/r7kamura
  9m:
    image_url: /images/actors/9m.png
    name: 9m
    url: https://twitter.com/9m
  soramugi:
    image_url: /images/actors/soramugi.jpg
    name: soramugi
    url: https://twitter.com/soramugi
  itopoid:
    image_url: /images/actors/itopoid.png
    name: itopoid
    url: https://twitter.com/itopoid
  hotchemi:
    image_url: /images/actors/hotchemi.png
    name: hotchemi
    url: https://twitter.com/hotchemi
  gong023:
    image_url: /images/actors/gong023.jpg
    name: gong023
    url: https://twitter.com/gong023
  Biacco42:
    image_url: /images/actors/Biacco42.png
    name: Biacco42
    url: https://twitter.com/Biacco42
  ninjinkun:
    image_url: /images/actors/ninjinkun.png
    name: ninjinkun
    url: https://twitter.com/ninjinkun
  kir1ca:
    image_url: /images/actors/kir1ca.jpg
    name: kir1ca
    url: https://twitter.com/kir1ca
  sukechansan:
    image_url: /images/actors/sukechansan.jpg
    name: sukechansan
    url: https://twitter.com/sukechansan
  NONUMBERLESS:
    image_url: /images/actors/NONUMBERLESS.jpg
    name: NONUMBERLESS
    url: http://nonumberless.com/
  ntddk:
    image_url: /images/actors/ntddk.jpg
    name: ntddk
    url: https://twitter.com/ntddk
  mizchi:
    image_url: /images/actors/mizchi.jpg
    name: mizchi
    url: https://twitter.com/mizchi
android_podcast_subscription_url: http://subscribeonandroid.com/yatteiki.fm/feed.xml
author: やっていき手
description: やっていき手のためのラジオ
description_long: ものづくり、仕事、生活などをやっていく話題を中心に、いま現在やっている人達が話す、やっていき手のためのラジオ
email: soramugi.chika@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
hashtag: yatteikifm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/yatteiki.fm/id1170904671?mt=2
keywords: tech,technology,yatteiki,programming,mobile,web,development,developer,software
language: ja
markdown: kramdown
permalink: /episode/:title
pushdog_subscription_url: https://push.dog/subscribe?url=https%3A%2F%2Fyatteiki.fm%2Ffeed.xml
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: yatteiki.fm
url: https://yatteiki.fm
